#' Fit Sub State ISVM
#'
#' Helper function to fit ISVM for single states
#'
#' @import data.table
#'
#' @param DT_subs_list A data set generated by the `make_subset` function.
#' @param DT_subs  A data.table with structure as provided in the example.
#' @param states  A data.table with the states of each observation.
#' @param select_bandwidth Boolean value. Should the optimal bandwidth for the local polynomial kernel regression be selected automatically? If TRUE, bandwidth will be selected according to least-squares cross-validation. Defaults to FALSE.
#' @param n_boottrial How many bootstrap iterations should be run?
#' @param subs Number of dates to subset the input data from. Defaults to 5.
#' @param verbose Boolean value. Should the function be verbose?
#' @param impute Boolean value. Should missing observations be imputed? Defaults to TRUE.
#' @param threshold How many percent of observations are allowed to be missing for each individual instrument over the observed timeframe? E.g. if set to 0.9, we allow 10% of observations to be missing. Defaults to 0.66.
#' @param state The state for which the model should be calculated
#' @param return_np_estimation_pars Should the fitted estimation parameters be returned? Defaults to `FALSE`.
#' @param return_lm Should the fitted object be returned? Defaults to `FALSE`.
#' @param return_lm_boot Should the bootstrap fitted object be returned? Only works if `return_lm = FALSE`. Defaults to `FALSE`.
#'
#' @return Output: An ISVM model for the sub state

#' @export
fit_sub_state_ISVM <- function(DT_subs_list,
                               DT_subs,
                               states,
                               n_boottrial = 500,
                               select_bandwidth = F,
                               verbose = F,
                               subs = 5,
                               threshold = 0,
                               impute = F,
                               state = NA,
                               return_np_estimation_pars = FALSE,
                               return_lm = FALSE,
                               return_lm_boot = FALSE){

  if (any(is.na(state)) || !exists("state")) {
    message("Error: state must be defined")
    return(list())
  }

  ## get data set ##
  DT_subs_list$train_data[,state := states[seq(nrow(DT_subs_list$train_data)),state]]
  DT_ISVM <- make_ISVM_data2(DT_subs_list,
                             DT_subs,
                             verbose = F,
                             subs = subs,
                             threshold = threshold,
                             impute = F,
                             state = state)

  ## fit model ##
  cat("\n")
  print(paste("Fitting model for state", paste(as.character(state), collapse = ',')))
  cat("\n")

  tryCatch(expr = {
    DT_res <- get_np_estimation(DT_ISVM = DT_ISVM,
                                boottrials = n_boottrial,
                                select_bandwidth = select_bandwidth,
                                return_np_estimation_pars = return_np_estimation_pars,
                                return_lm = return_lm,
                                return_lm_boot = return_lm_boot)
    return(DT_res)
  }, error = function(e) {
    message("Error: ")
    print(e)
    DT_res <- list()
    return(DT_res)
  })
}
